import type { Preset, ProcessSettings } from "./types";

export const DEFAULT_SETTINGS: ProcessSettings = {
  dotSize: 1,
  dotSpacing: 5.5,
  dotDensity: 1.05,
  dotSharpness: 0.82,
  minDotSize: 0,
  maxDotSize: 1.12,
  brightness: 0.02,
  contrast: 1.28,
  exposure: 1.06,
  threshold: 0.045,
  gamma: 0.92,
  invert: false,
  resolution: "medium",
  ditherMode: "halftone",
  smoothing: 0.32,
  edgeEnhance: 0.22,
  dotColor: "#ffffff",
};

export const PRESETS: Preset[] = [
  {
    id: "classic",
    name: "Classic Halftone",
    hint: "Balanced size and spacing",
    settings: { ...DEFAULT_SETTINGS },
  },
  {
    id: "fine",
    name: "Fine Dots",
    hint: "Small dots, high detail",
    settings: {
      ...DEFAULT_SETTINGS,
      dotSize: 0.85,
      dotSpacing: 3.4,
      dotDensity: 1.15,
      minDotSize: 0.08,
      maxDotSize: 1.05,
      resolution: "high",
      smoothing: 0.18,
      edgeEnhance: 0.28,
      contrast: 1.22,
    },
  },
  {
    id: "bold",
    name: "Bold",
    hint: "Large dots, strong forms",
    settings: {
      ...DEFAULT_SETTINGS,
      dotSize: 1.25,
      dotSpacing: 9.5,
      dotDensity: 1.1,
      minDotSize: 0.12,
      maxDotSize: 1.28,
      contrast: 1.45,
      threshold: 0.06,
      edgeEnhance: 0.35,
      resolution: "medium",
    },
  },
  {
    id: "contrast",
    name: "High Contrast",
    hint: "Deep blacks, bright hits",
    settings: {
      ...DEFAULT_SETTINGS,
      contrast: 1.85,
      exposure: 1.12,
      threshold: 0.12,
      gamma: 1.15,
      dotSpacing: 5.2,
      maxDotSize: 1.22,
      minDotSize: 0,
      edgeEnhance: 0.4,
      smoothing: 0.2,
    },
  },
  {
    id: "sketchy",
    name: "Sketchy Dither",
    hint: "Aggressive ordered grain",
    settings: {
      ...DEFAULT_SETTINGS,
      ditherMode: "ordered",
      dotSpacing: 3.2,
      dotSize: 0.92,
      maxDotSize: 0.95,
      minDotSize: 0.55,
      contrast: 1.35,
      threshold: 0.03,
      dotDensity: 1.2,
      resolution: "high",
      smoothing: 0.12,
      edgeEnhance: 0.18,
    },
  },
  {
    id: "live",
    name: "Live Camera",
    hint: "Tuned for real-time",
    settings: {
      ...DEFAULT_SETTINGS,
      resolution: "medium",
      dotSpacing: 6,
      dotSize: 1.02,
      smoothing: 0.48,
      edgeEnhance: 0.16,
      threshold: 0.07,
      contrast: 1.32,
      maxDotSize: 1.1,
    },
  },
  {
    id: "stipple",
    name: "Stipple",
    hint: "Stable density field",
    settings: {
      ...DEFAULT_SETTINGS,
      ditherMode: "stipple",
      dotSpacing: 4.6,
      dotSize: 0.95,
      minDotSize: 0.35,
      maxDotSize: 1.05,
      dotDensity: 1.25,
      contrast: 1.3,
      resolution: "high",
    },
  },
  {
    id: "newsprint",
    name: "Newsprint",
    hint: "Error-diffused print",
    settings: {
      ...DEFAULT_SETTINGS,
      ditherMode: "floyd",
      dotSpacing: 4.2,
      dotSize: 0.88,
      minDotSize: 0.45,
      maxDotSize: 1,
      contrast: 1.4,
      threshold: 0.05,
      resolution: "high",
      smoothing: 0.22,
    },
  },
];

export const DOT_COLORS: { name: string; value: string }[] = [
  { name: "White", value: "#ffffff" },
  { name: "Cyan", value: "#7df0ff" },
  { name: "Green", value: "#70ff9a" },
  { name: "Pink", value: "#ff7ad9" },
  { name: "Blue", value: "#6aa8ff" },
  { name: "Amber", value: "#ffd36a" },
];

export const RESOLUTION_WIDTH: Record<ProcessSettings["resolution"], number> = {
  low: 280,
  medium: 480,
  high: 720,
  ultra: 1024,
};
